version: "3"
services:
  web:
    image: anweshpatel/usn:charcoal-0.0.2-arm
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
    volumes: 
      - "/DB:/app/DB"

networks:
  webnet:
